apiVersion: v1
kind: Service
metadata:
  name: {{ include "yugabyte.fullname" . }}-master
  labels:
    {{- include "yugabyte.labels" . | nindent 4 }}
    component: master
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - port: 7000
    name: master-ui
    targetPort: master-ui
  - port: 7100
    name: master-rpc
    targetPort: master-rpc
  selector:
    {{- include "yugabyte.selectorLabels" . | nindent 4 }}
    component: master