{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hyperswitch-server.name" . }}
spec:
  scaleTargetRef:
    {{- if .Values.server.rollout.enabled }}
    # Target Argo Rollout resource when rollouts are enabled
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    # Target standard Deployment when rollouts are disabled
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "hyperswitch-server.name" . }}
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
{{- end }}
