{{- if .Values.externalSecretsOperator.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecretsOperator.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    {{- toYaml .Values.externalSecretsOperator.secretStore.provider | nindent 4 }}
{{- end }}
