{{- if and .Values.externalSecretsOperator.enabled .Values.externalSecretsOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecretsOperator.serviceAccount.name | default "encryption-service-eso-sa" }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalSecretsOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hyperswitch-encryption-service.labels" . | nindent 4 }}
    {{- with .Values.externalSecretsOperator.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
