{{- if and .Values.istio.enabled .Values.istio.virtualService.create }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-hyperswitch-vs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperswitch.labels" . | nindent 4 }}
    app.kubernetes.io/component: istio-virtual-service
spec:
  {{- if .Values.istio.virtualService.hosts }}
  hosts:
  {{- toYaml .Values.istio.virtualService.hosts | nindent 2 }}
  {{- end }}
  {{- if .Values.istio.virtualService.gateways }}
  gateways:
  {{- toYaml .Values.istio.virtualService.gateways | nindent 2 }}
  {{- end }}
  {{- if or .Values.istio.virtualService.http.router .Values.istio.virtualService.http.controlCenter }}
  http:
  {{- if .Values.istio.virtualService.http.router }}
  {{- range .Values.istio.virtualService.http.router }}
  - match:
    {{- toYaml .match | nindent 4 }}
    route:
      - destination:
          host: {{ include "hyperswitch-server.name" . }}
          subset: {{ include "version.suffix" $.Values.services.router.version }}
          port:
            number: 80
    {{- if .timeout }}
    timeout: {{ .timeout }}
    {{- end }}
    {{- if .retries }}
    retries:
      {{- toYaml .retries | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.istio.virtualService.http.controlCenter }}
  {{- range .Values.istio.virtualService.http.controlCenter }}
  - match:
    {{- toYaml .match | nindent 4 }}
    route:
      - destination:
          host: {{ include "hyperswitch-control-center.name" . }}
          subset: {{ include "version.suffix" .Values.services.controlCenter.version }}
          port:
            number: 80
    {{- if .timeout }}
    timeout: {{ .timeout }}
    {{- end }}
    {{- if .retries }}
    retries:
      {{- toYaml .retries | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
