{{- if and .Values.externalSecretsOperator.enabled .Values.externalSecretsOperator.serviceAccount.create }}
{{- $serviceAccountName := .Values.externalSecretsOperator.serviceAccount.name | default "hyperswitch-eso-sa" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperswitch.labels" . | nindent 4 }}
    {{- with .Values.externalSecretsOperator.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.externalSecretsOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
