{{- if and .Values.services.controlCenter.enabled .Values.controlCenter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  {{- with .Values.controlCenter.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with .Values.controlCenter.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "hyperswitch-control-center-sa.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
