[common]
environment = "production"

[log.console]
enabled = true
level = "TRACE"
log_format = "default"

[server]
host = "0.0.0.0"
port = 8000
type = "grpc"

[metrics]
host = "0.0.0.0"
port = 8080

[proxy]
idle_pool_connection_timeout = 90               # Timeout for idle pool connections (defaults to 90s)
bypass_proxy_urls = ["localhost", "local"]
mitm_proxy_enabled = false

[connectors]
mollie.base_url = "https://api.mollie.com/v2"
mollie.secondary_base_url = "https://api.cc.mollie.com/v1/"
gigadat.base_url = "https://interac.express-connect.com/"
paybox.base_url = "https://ppps.paybox.com/PPPS.php"
loonio.base_url = "https://loonio.ca/"
getnet.base_url = "https://api.pre.globalgetnet.com"
payme.base_url = "https://live.payme.io/api/"
hyperpg.base_url = "https://api.hyperpg.in"
barclaycard.base_url = "https://api.smartpayfuse.barclaycard"
airwallex.base_url = "https://api.airwallex.com/api/v1"
bambora.base_url = "https://api.na.bambora.com/v1"
shift4.base_url = "https://api.shift4.com"
bluesnap.base_url = "https://ws.bluesnap.com"
bluesnap.secondary_base_url = "https://pay.bluesnap.com"
multisafepay.base_url = "https://testapi.multisafepay.com/v1/json"
iatapay.base_url = "https://iata-pay.iata.org/api/v1"
jpmorgan.base_url = "https://api-ms.payments.jpmorgan.com/api/v2"
jpmorgan.secondary_base_url = "https://id.payments.jpmorgan.com"
nmi.base_url = "https://secure.nmi.com"
nexixpay.base_url = "https://xpay.nexigroup.com/api/phoenix-0.0/psp/api/v1"
authipay.base_url = "https://prod.emea.api.fiservapps.com/ipp/payments-gateway/v2/payments"
stax.base_url = "https://apiprod.fattlabs.com"
trustpayments.base_url = "https://webservices.securetrading.net"
fiservemea.base_url = "https://prod.emea.api.fiservapps.com/ipp/payments-gateway/v2/payments"
datatrans.base_url = "https://api.datatrans.com"
silverflow.base_url = "https://api.silverflow.co/v1"
celero.base_url = "https://app.gotnpgateway.com"
hipay.base_url = "https://secure-gateway.hipay-tpp.com/rest/"
hipay.secondary_base_url = "https://secure2-vault.hipay-tpp.com/rest/v2/token"
hipay.third_base_url = "https://api-gateway.hipay.com/"
globalpay.base_url = "https://apis.globalpay.com/ucp"
adyen.base_url = "https://{{merchant_endpoint_prefix}}-checkout-live.adyenpayments.com/checkout/"
adyen.dispute_base_url = "https://{{merchant_endpoint_prefix}}-ca-live.adyen.com/"
razorpay.base_url = "https://api.razorpay.com/"
razorpayv2.base_url = "https://api.razorpay.com/"
fiserv.base_url = "https://cert.api.fiservapps.com/"
elavon.base_url = "https://api.convergepay.com/VirtualMerchant/"
xendit.base_url = "https://api.xendit.co"
checkout.base_url = "https://api.sandbox.checkout.com/"
authorizedotnet.base_url = "https://api.authorize.net/xml/v1/request.api"
phonepe.base_url = "https://api.phonepe.com/apis/hermes/"
cashfree.base_url = "https://sandbox.cashfree.com/"
fiuu.base_url = "https://pay.merchant.razer.com/"
fiuu.secondary_base_url = "https://api.merchant.razer.com/"
fiuu.third_base_url="https://api.merchant.razer.com/"
payload.base_url = "https://api.payload.com"
forte.base_url = "https://api.forte.net/v3"
payu.base_url = "https://secure.payu.com/api/"
paytm.base_url = "https://secure.paytmpayments.com/"
cashtocode.base_url = "https://cluster14.api.cashtocode.com"
novalnet.base_url = "https://payport.novalnet.de/v2"
nexinets.base_url = "https://api.payengine.de/v1"
noon.base_url = "https://api.noonpayments.com/"
mifinity.base_url = "https://secure.mifinity.com/"
braintree.base_url = "https://payments.braintree-api.com/graphql"
volt.base_url = "https://gateway.volt.io"
volt.secondary_base_url = "https://api.volt.io/"
calida.base_url = "https://app.eorder.reloadhero.com/"
cryptopay.base_url = "https://business.cryptopay.me/"
helcim.base_url = "https://api.helcim.com/"
dlocal.base_url = "https://api.dlocal.com/"
placetopay.base_url = "https://checkout.placetopay.com/rest/gateway"
rapyd.base_url = "https://api.rapyd.net"
redsys.base_url = "https://sis.redsys.es"
aci.base_url = "https://eu-prod.oppwa.com/"
trustpay.base_url = "https://tpgw.trustpay.eu/"
trustpay.base_url_bank_redirects = "https://aapi.trustpay.eu/"
stripe.base_url = "https://api.stripe.com/"
cybersource.base_url = "https://api.cybersource.com/"
worldpay.base_url = "https://access.worldpay.com/"
worldpayvantiv.base_url = "https://transact.vantivcnp.com/vap/communicator/online"
worldpayvantiv.secondary_base_url = "https://onlinessr.vantivcnp.com"
bamboraapac.base_url = "https://www.bambora.co.nz/interface/api"
paypal.base_url = "https://api-m.paypal.com/"
paysafe.base_url = "https://api.paysafe.com/paymenthub/"
billwerk.base_url = "https://api.reepay.com/"
billwerk.secondary_base_url = "https://card.reepay.com/"
nuvei.base_url = "https://secure.safecharge.com/ppp/api/v1"
worldpayxml.base_url = "https://secure.worldpay.com/jsp/merchant/xml/paymentService.jsp"
tsys.base_url = "https://gateway.transit-pass.com/"
bankofamerica.base_url = "https://apitest.merchant-services.bankofamerica.com/"
powertranz.base_url = "https://staging.ptranz.com/api"
revolut.base_url = "https://oba-auth.revolut.com/"
wellsfargo.base_url = "https://api.cybersource.com/"
zift.base_url = "https://secure.zift.io/"

# Generic Events Configuration
[events]
enabled = false
brokers = ["localhost:9092"]
topic = "audit-trail-events"
partition_key_field = "request_id"

[unmasked_headers]
keys = ["x-request-id","x-merchant-id","x-lineage-ids","x-reference-id","x-connector","x-tenant-id","x-shadow-mode"]
