{{- if .Values.sdkDemo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sdkDemo.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: {{ .Values.sdkDemo.service.ports.http }}
      protocol: TCP
      targetPort: 5252
    - name: https
      port: {{ .Values.sdkDemo.service.ports.https }}
      protocol: TCP
      targetPort: 5252
  selector:
    app: {{ .Values.sdkDemo.labels.app }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
