{{- if .Values.externalSecretsOperator.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecretsOperator.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .Values.externalSecretsOperator.secretStore.provider | nindent 2 }}
{{- end }}
