apiVersion: v2
name: hyperswitch-ucs
description: A Helm chart for Hyperswitch UCS Service
type: application
version: 0.1.3-ucs-2025-12-24-0
AppVersion: "0.1.0"
keywords:
  - ucs
  - service
  - grpc
