{{- if .Values.services.drainer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperswitch-drainer.name" . }}-{{ .Values.services.drainer.version | replace "." "o" }}
  namespace: {{ include "drainer.namespace" . }}
  labels:
    {{- include "hyperswitch.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "hyperswitch-drainer.name" . }}
    app.kubernetes.io/version: {{ .Values.services.drainer.version }}
    app: {{ include "hyperswitch-drainer.name" . }}
    version: {{ include "version.suffix" .Values.services.drainer.version }}
spec:
  replicas: {{ .Values.drainer.replicas }}
  progressDeadlineSeconds: {{ .Values.drainer.progressDeadlineSeconds | default .Values.global.progressDeadlineSeconds }}
  strategy:
    {{- toYaml (.Values.drainer.strategy | default .Values.global.strategy) | nindent 4 }}
  selector:
    matchLabels:
      app: {{ include "hyperswitch-drainer.name" . }}
      version: {{ include "version.suffix" .Values.services.drainer.version }}
  template:
    metadata:
      annotations:
        checksum/drainer-cm: {{ include (print $.Template.BasePath "/drainer/configmap.yaml") . | sha256sum }}
        checksum/drainer-secret: {{ include (print $.Template.BasePath "/drainer/secret.yaml") . | sha256sum }}
        {{- with (.Values.drainer.podAnnotations | default .Values.global.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: {{ include "hyperswitch-drainer.name" . }}
        version: {{ include "version.suffix" .Values.services.drainer.version }}
        {{- include "hyperswitch.labels" . | nindent 8 }}
        {{- with (.Values.drainer.labels | default .Values.global.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.drainer.affinity | default .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.drainer.terminationGracePeriodSeconds | default .Values.global.terminationGracePeriodSeconds }}
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
        {{- if .Values.redisMiscConfig.checkRedisIsUp.initContainer.enable }}
        {{- include "redis.initContainer.check.ready" . | nindent 8 }}
        {{- end }}
      containers:
        - name: hyperswitch-drainer
          {{- $registry := .Values.global.imageRegistry | default .Values.services.drainer.imageRegistry }}
          image: "{{ $registry }}/{{ .Values.services.drainer.image }}:{{ .Values.services.drainer.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          {{- if .Values.drainer.resources }}
          resources:
            {{- toYaml .Values.drainer.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.global.useExternalSecrets.enabled }}
            {{- include "external.secrets.envs" . | nindent 12 }}
            {{- else }}
            {{- include "drainer.secrets.envs" . | nindent 12}}
            {{- end }}
            {{- include "generic.envs" . | nindent 12 }}
            {{- include "keymanager.envs" . | nindent 12 }}
            {{- range $key, $value := .Values.drainer.env }}
            {{- if kindIs "string" $value }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- else }}
            - name: {{ $key }}
              {{- toYaml $value | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- include "hyperswitch.configToEnvRefs" (dict "config" .Values.drainer.configs "prefix" "DRAINER" "context" .) | nindent 12 }}
          envFrom:
            - configMapRef:
                name: drainer-cm-{{ .Release.Name }}
          {{- if not .Values.global.useExternalSecrets.enabled }}
            - secretRef:
                name: drainer-secret-{{ .Release.Name }}
          {{- end }}
      serviceAccountName: {{ include "hyperswitch-router-sa.name" . }}
{{- end }}
