{{- if .Values.services.drainer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperswitch-drainer-{{ .Values.services.drainer.version | replace "." "o" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperswitch.labels" . | nindent 4 }}
    app: hyperswitch-drainer
    version: {{ .Values.services.drainer.version | replace "." "o" }}
spec:
  replicas: {{ .Values.drainer.replicas }}
  progressDeadlineSeconds: {{ .Values.drainer.progressDeadlineSeconds | default .Values.global.progressDeadlineSeconds }}
  strategy:
    {{- toYaml (.Values.drainer.strategy | default .Values.global.strategy) | nindent 4 }}
  selector:
    matchLabels:
      app: hyperswitch-drainer
      version: {{ .Values.services.drainer.version | replace "." "o" }}
  template:
    metadata:
      annotations:
        checksum/drainer-cm: {{ include (print $.Template.BasePath "/drainer/configmap.yaml") . | sha256sum }}
        checksum/drainer-secret: {{ include (print $.Template.BasePath "/drainer/secret.yaml") . | sha256sum }}
        {{- with (.Values.drainer.podAnnotations | default .Values.global.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: hyperswitch-drainer
        version: {{ .Values.services.drainer.version | replace "." "o" }}
        {{- include "hyperswitch.labels" . | nindent 8 }}
        {{- with (.Values.drainer.labels | default .Values.global.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.drainer.affinity | default .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.drainer.terminationGracePeriodSeconds | default .Values.global.terminationGracePeriodSeconds }}
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
        {{- if .Values.redisMiscConfig.checkRedisIsUp.initContainer.enable }}
        {{- include "redis.initContainer.check.ready" . | nindent 8 }}
        {{- end }}
      containers:
        - name: hyperswitch-drainer
          image: {{ .Values.services.drainer.image }}
          imagePullPolicy: Always
          command:
            - /local/bin/drainer
            - -f
            {{- if eq .Values.server.run_env "production" }}
            - /local/config/production.toml
            {{- else }}
            - /local/config/sandbox.toml
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          {{- if .Values.drainer.resources }}
          resources:
            {{- toYaml .Values.drainer.resources | nindent 12 }}
          {{- end }}
          env:
            {{- include "drainer.secrets.envs" . | nindent 12}}
            {{- include "generic.envs" . | nindent 12 }}
            {{- include "keymanager.envs" . | nindent 12 }}
            {{- range $key, $value := .Values.drainer.env }}
            {{- if kindIs "string" $value }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- else }}
            - name: {{ $key }}
              {{- toYaml $value | nindent 14 }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: drainer-secret-{{ .Release.Name }}
          volumeMounts:
            {{- if eq .Values.server.run_env "production" }}
            - mountPath: /local/config/production.toml
              name: hyperswitch-config
              subPath: drainer.toml
            {{- else }}
            - mountPath: /local/config/sandbox.toml
              name: hyperswitch-config
              subPath: drainer.toml
            {{- end }}
      volumes:
        - name: hyperswitch-config
          configMap:
            name: drainer-cm-{{ .Release.Name }}
{{- end }}
