{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "hyperswitch-control-center.fullname" . }}-dr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperswitch-control-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: istio-destination-rule
spec:
  host: {{ include "hyperswitch-control-center.fullname" . }}
  {{- if .Values.image.tag }}
  subsets:
    - name: {{ include "version.suffix" .Values.image.tag }}
      labels:
        version: {{ include "version.suffix" .Values.image.tag }}
  {{- end }}
  {{- if .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  {{- end }}
{{- end }}
