apiVersion: v1
kind: Secret
metadata:
  name: producer-secret-{{.Release.Name }}
data:
  ROUTER__FILE_UPLOAD_CONFIG__BUCKET_NAME: {{ "bucket" | b64enc }}
  ROUTER__FILE_UPLOAD_CONFIG__REGION: {{ "us-east-1"  | b64enc }}
  ROUTER__API_KEYS__HASH_KEY: {{ "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" | b64enc }}
  ROUTER__ANALYTICS__SQLX__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__HOST: {{ include "postgresqlreplica.host" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__PORT: {{ include "postgresqlreplica.port" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__DATABASE_NAME: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__MASTER_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__MASTER_DATABASE__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__MASTER_DATABASE__PORT: {{ include "postgresql.port" . | toString | b64enc }}
  ROUTER__MASTER_DATABASE__USERNAME: {{ include "postgresql.username" . | b64enc }}
  ROUTER__REPLICA_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__REPLICA_DATABASE__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__REPLICA_DATABASE__PORT: {{ include "postgresql.port" . | toString | b64enc }}
  ROUTER__REPLICA_DATABASE__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__REDIS__HOST: {{ include "redis.host" .  | b64enc }}
  ROUTER__REDIS__PORT: {{ include "redis.port" . | toString | b64enc }}
  ROUTER__SECRETS__ADMIN_API_KEY: {{ .Values.application.server.secrets.admin_api_key | b64enc }}
  ROUTER__SECRETS__JWT_SECRET: {{ .Values.application.server.secrets.jwt_secret | b64enc }}
  ROUTER__SECRETS__MIGRATION_ENCRYPTION_TIMESTAMP: {{ "1685510751" | b64enc }}

