apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdk.fullname" . }}
  labels:
    {{- include "sdk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sdk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdk.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sdk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: build-and-copy
          {{- $registry := .Values.global.imageRegistry | default .Values.autoBuild.imageRegistry }}
          image: "{{ $registry }}/{{ .Values.autoBuild.image }}:v{{ .Values.autoBuild.gitCloneParam.gitVersion | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.autoBuild.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Building static files..."
              npm run re:build
              npm run build:{{ .Values.env.sdkEnv }}
              echo "Copying built files to nginx path..."
              mkdir -p /usr/share/nginx/html{{ include "nginx.sdk.path" . }}
              cp -r /usr/src/app/dist/{{ .Values.env.sdkEnv }}/{{ include "hyperswitch-sdk.subversion" . }}/* /usr/share/nginx/html{{ include "nginx.sdk.path" . }}
              echo "Build and copy completed successfully"
              ls -la /usr/share/nginx/html{{ include "nginx.sdk.path" . }}
          env:
            - name: sdkEnv
              value: "{{ .Values.env.sdkEnv }}"
            - name: ENV_SDK_URL
              value: "{{ .Values.autoBuild.buildParam.envSdkUrl }}"
            - name: ENV_BACKEND_URL
              value: "{{ .Values.autoBuild.buildParam.envBackendUrl }}"
            - name: ENV_LOGGING_URL
              value: "{{ .Values.autoBuild.buildParam.envLogsUrl }}"
            - name: ENABLE_LOGGING
              value: "{{ .Values.env.enableLogging }}"
            - name: DISABLE_CSP
              value: "{{ .Values.autoBuild.buildParam.disableCSP }}"
            - name: SDK_VERSION
              value: "{{ .Values.env.sdkVersion }}"
            - name: SDK_TAG_VERSION
              value: "{{ .Values.env.sdkTagVersion }}"
            - name: SENTRY_DSN
              value: "{{ .Values.env.sentryDsn }}"
            - name: VISA_API_KEY_ID
              value: "{{ .Values.env.visaApiKeyId }}"
            - name: VISA_API_CERTIFICATE_PEM
              value: "{{ .Values.env.visaApiCertificatePem }}"
            - name: PORT
              value: "{{ .Values.service.port }}"
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- $registry := .Values.global.imageRegistry | default .Values.autoBuild.nginxConfig.imageRegistry }}
          image: "{{ $registry }}/{{ .Values.autoBuild.nginxConfig.image }}:{{ .Values.autoBuild.nginxConfig.tag }}"
          imagePullPolicy: {{ .Values.autoBuild.nginxConfig.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ include "nginx.sdk.path" . }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ include "nginx.sdk.path" . }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
